### ISSUE TITLE
Can't enable debug logging

### ISSUE THREAD

**Issue by pmembrey** [willemt/raft#11]
Hi,

As described in another issue, changing ```#if 0 /* debugging */``` to ```#if 1 /* debugging */``` fails to compile due to duplicate definitions and undefined functions. The line is:

https://github.com/willemt/raft/blob/master/src/raft_server.c#L36

Cheers,

Pete

**Comment by willemt** [comment]
Sorry it looks like the debug code inside that function was bad. I've removed it now.

The best way to enable the logging functions is to implement the "log" function callback.

eg.

```c
void __raft_log(raft_server_t* raft, void *udata, const char *buf)
{
    printf("log: '%s'\n", buf);
}

raft_cbs_t raft_funcs = {
    .send_requestvote            = __send_requestvote,
    .send_appendentries          = __send_appendentries,
    .applylog                    = __applylog,
    .log                         = __raft_log,
};
```

**Comment by pmembrey** [comment]
Implementing the log function as described in another issue solved this nicely :)
