### ISSUE TITLE
Log callback called every time raft_periodic is called

### ISSUE THREAD

**Issue by pmembrey** [willemt/raft#12]
Hi,

In my code I set ```election_timeout``` and ```request_timeout``` to say 5,000ms. I then call ```raft_periodic``` every 1,000ms. In my own callback ( the one that calls ```raft_periodic```) it prints ```PING!``` every time it is executed.

Previously, I would see five of these pings before the timeout was hit and raft started sending out vote requests. However in the latest version, every time I call ```raft_periodic``` it also calls the ```log``` function.

So two questions:

1. What does the ```log``` function actually do? It's not documented as far as I can tell...
2. Why is it being called each time?

Thanks!

Cheers,

Pete

**Comment by willemt** [comment]
1. `log` is really just for debugging purposes when you're implementing clients. All it does is pass event strings to the client. This is useful if you want to check if things are operating correctly. I think it's quite likely that we can remove this callback one day

2. I think this is a throw back to when I was writing tests for the timeout. I'm going to remove it as I think it might be a case of information overload

**Comment by pmembrey** [comment]
Awesome thanks for clearing that up :)
