### ISSUE TITLE
TestRaft_server_recv_requestvote_response_increase_votes_for_me problem

### ISSUE THREAD

**Issue by frozenxia** [willemt/raft#30]
in test_server.c

void TestRaft_server_recv_requestvote_response_increase_votes_for_me(
    CuTest * tc
    )
{
    void *r = raft_new();
    raft_add_node(r, NULL, 1, 1);
    raft_add_node(r, NULL, 2, 0);
    raft_set_current_term(r, 1);
    CuAssertTrue(tc, 0 == raft_get_nvotes_for_me(r));

### vote for myself ,so vote nums is 1

   raft_become_candidate(r);

    msg_requestvote_response_t rvr;
    memset(&rvr, 0, sizeof(msg_requestvote_response_t));
    rvr.term = 1;
    rvr.vote_granted = 1;
### recv vote response, so vote nums increases to 2
    raft_recv_requestvote_response(r, raft_get_node(r, 2), &rvr);

### maybe this should be 2
    CuAssertTrue(tc, 1 == raft_get_nvotes_for_me(r));
}

wonder is my understanding error, or a mistake ,thanks!

**Comment by willemt** [comment]
Hi I've already answered this in https://github.com/willemt/raft/issues/28 😄 

Please pull the latest version from Github?

**Comment by frozenxia** [comment]
sorry, i missed this.
