### ISSUE TITLE
heartbeat rpc might delete uncommited logs?

### ISSUE THREAD

**Issue by UncP** [willemt/raft#37]
consider this situation, leader sends a few logs(first rpc)  to follower, before the response return to the leader, a heartbeat rpc(second rpc) arrives this follower, the follower will delete first rpc's logs because the second rpc's prev_log_idx is the same as in first rpc, when the first rpc returns to the leader, it says logs replicated successfully, but in fact the logs have been deleted, so i think maybe we should not delete the logs when it is heartbeat.

in raft_server.c : raft_recv_appendentries: 385-389

    if (ae->n_entries == 0 && 0 < ae->prev_log_idx && ae->prev_log_idx + 1 < raft_get_current_idx(me_)) 
        { 
            assert(me->commit_idx < ae->prev_log_idx + 1); 
            raft_delete_entry_from_idx(me_, ae->prev_log_idx + 1); 
        }

**Comment by willemt** [comment]
thanks! I've confirmed the bug. I will add a fix in this PR: https://github.com/willemt/raft/pull/39
