### ISSUE TITLE
RequestVote structure not fully intialised

### ISSUE THREAD

**Issue by pmembrey** [willemt/raft#7]
Hi,
I'm new to the library, so please feel free to close this issue if this is not relevant. When I was sending a vote request, I noticed that last log term was always a large random number. I was expecting it to be zero at this stage.

In this piece of code:

https://github.com/willemt/raft/blob/master/src/raft_server.c#L422

```` c

int raft_send_requestvote(raft_server_t* me_, int node)
{
    raft_server_private_t* me = (raft_server_private_t*)me_;
    msg_requestvote_t rv;

    __log(me_, "sending requestvote to: %d", node);

    rv.term = me->current_term;
    rv.last_log_idx = raft_get_current_idx(me_);
    if (me->cb.send_requestvote)
        me->cb.send_requestvote(me_, me->udata, node, &rv);
    return 0;
}
````
`rv` isn't zero'd and `rv.last_log_term` is never explicitly set.

Thanks in advance!

Cheers,

Pete

**Comment by willemt** [comment]
Hi thanks for spotting this! it's a bug. I'm closing with this fix: https://github.com/willemt/raft/commit/5adcd8bae927b0f7a43b66003a503e2e84017025
