### ISSUE TITLE
Invalid term returned after calling raft_recv_requestvote

### ISSUE THREAD

**Issue by pmembrey** [willemt/raft#9]
Hi,

When called `raft_recv_requestvote`, the `msg_requestvote_response_t` that I get back has a garbled term. For example I had a long running app on term 180. I started up the test app and it started at term 1. The test app received a RequestVote message from the long running app. However then the test app replied with a No vote and with term 428825 (or similar - I don't have it in front of me right now).

I haven't yet been able to track down where this number is coming from...

Cheers,

Pete

PS I sent you an email a week or so go but didn't get a reply - not sure if it got stuck in a spam filter somewhere...

**Comment by willemt** [comment]
Thanks for highlighting this, I'll have a look into it

BTW, your email did get caught by a spam filter sorry. I'll reply to it soon :smile:

**Comment by pmembrey** [comment]
I was running it on Manjaro (based on Arch Linux) and I'm using the clang compiler. I just gave it a go on my Ubuntu laptop and the tests build and run, but stop with an error at the end:

    ok 59 - TestRaft_leader_sends_appendentries_with_NextIdx_when_PrevIdx_gt_NextIdx
    ok 60 - TestRaft_leader_append_entry_to_log_increases_idxno
    ok 61 - TestRaft_leader_steps_down_if_received_appendentries_is_newer_than_itself
    
    gcov src/raft_server.c
    src/raft_server.gcno:cannot open notes file
    $

I'll fiddle about some more on my main machine tonight - looks like it could be something to do with my set up...

**Comment by willemt** [comment]
Looks like it works on your Ubuntu laptop. The remaining error (ie. raft_server.gcno:cannot open notes file) doesn't effect the test suite, it just seems to have some trouble displaying the test coverage

**Comment by pmembrey** [comment]
Turned out the raft_server pointer being passed in was corrupt. The values created by the code were correct for the bad data I passed in. Garbage in, garbage out.

Not a bug in craft so closing out.
